# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ed36eb685e3a95a5a59aef6554b8b08c1e2116a8bdb6e36a9d67ab3f2f8e91be1410a7edb6b95e54a7f08425c7d7ad0bcb1e94ebba3d7e2bdabf534ef399e5

test:
  secret_key_base: c4754dff6e72313d8f9dd9dbc6e396ce455351ea3b83dcdf417532e3e430c4b0fe160d7e4e795c29690ff7cf9bd0f6efb5baed1c9fa627b484c40dccb0f7954b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
